Updating recipe.
AnacondaRecipes/google-resumable-media-feedstock pull request #10
Opened 2022-10-24 22:39 UTC by ryanskeith

# Changes
---
- Updated Version, hash
- Reset build number
- Removed noarch and added Python requirements via skip
- Removed six dependency
- Added license url
- Changed doc_url

# Notes
---
- The old doc_url was broken completely.  The new one, even though pointed to the latest, is actually out of date but It think this is the best we can do.

2022-11-08 22:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_e0ubkhmt55/clone/recipe/meta.yaml:10: invalid_url: https://pypi.org/packages/source/g/google-resumable-media/google-resumable-media-2.4.0.tar.gz : URL domain redirect pypi.org ->  files.pythonhosted.org
WARNING: /tmp/abs_e0ubkhmt55/clone/recipe/meta.yaml:48: missing_description: The recipe is missing a description
WARNING: /tmp/abs_e0ubkhmt55/clone/recipe/meta.yaml:48: missing_doc_source_url: The recipe is missing a doc_source_url
Errors were found

</details>

2022-11-08 23:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_87g5g02mmb/clone/recipe/meta.yaml:10: invalid_url: https://pypi.org/packages/source/g/google-resumable-media/google-resumable-media-2.4.0.tar.gz : URL domain redirect pypi.org ->  files.pythonhosted.org
WARNING: /tmp/abs_87g5g02mmb/clone/recipe/meta.yaml:49: missing_doc_source_url: The recipe is missing a doc_source_url
Errors were found

</details>

2022-11-09 06:21 UTC, katietz requested changes
with that change, I will approve

2022-11-09 06:21 UTC, katietz commented on recipe/meta.yaml
> +  license_url: https://github.com/googleapis/google-resumable-media-python/blob/v2.4.0/LICENSE
no need for a license_url as we have already in package ficense_file.  This tag is superflous

2022-11-10 17:24 UTC, varlackc reviewed
We need to have two white spaces between `True` and the `#` symbol
also we need a white space between the `#` symbol and the `[py<37]` section
https://github.com/AnacondaRecipes/google-resumable-media-feedstock/blob/c5135759ff2e94dec881b23068e3fcdf3ca71340/recipe/meta.yaml#L14

2022-11-11 19:32 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_ceamxo4hlk/clone/recipe/meta.yaml:10: invalid_url: https://pypi.org/packages/source/g/google-resumable-media/google-resumable-media-2.4.0.tar.gz : URL domain redirect pypi.org ->  files.pythonhosted.org
WARNING: /tmp/abs_ceamxo4hlk/clone/recipe/meta.yaml:49: missing_doc_source_url: The recipe is missing a doc_source_url
Errors were found

</details>

2022-11-11 23:07 UTC, merged